[package]
name = "slide89"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
reqwest = { version = "0.12.7", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }